FROM node:18-alpine

WORKDIR /app

COPY ./package*.json ./

RUN npm install

ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_TOKEN_COOKIE_KEY
ARG NEXT_PUBLIC_MAPBOX_TOKEN
ARG NEXT_PUBLIC_ASSETS_URL
ARG NEXT_AUTH_KEY

ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
ENV NEXT_PUBLIC_TOKEN_COOKIE_KEY=${NEXT_PUBLIC_TOKEN_COOKIE_KEY}
ENV NEXT_PUBLIC_ASSETS_URL=${NEXT_PUBLIC_ASSETS_URL}
ENV NEXT_AUTH_KEY=${NEXT_AUTH_KEY}

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]