import type { Config } from "tailwindcss";
const colors = require("tailwindcss/colors");
const plugin = require("tailwindcss/plugin");

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    colors: {
      ...colors,
      blue: {
        950: "var(--blue-95)",
        900: "var(--blue-90)",
        800: "var(--blue-80)",
        700: "var(--blue-70)",
        600: "var(--blue-60)",
        500: "var(--blue-50)",
        400: "var(--blue-40)",
        300: "var(--blue-30)",
        200: "var(--blue-20)",
        100: "var(--blue-10)",
        50: "var(--blue-5)",
      },
      red: {
        950: "var(--red-95)",
        900: "var(--red-90)",
        800: "var(--red-80)",
        700: "var(--red-70)",
        600: "var(--red-60)",
        500: "var(--red-50)",
        400: "var(--red-40)",
        300: "var(--red-30)",
        200: "var(--red-20)",
        100: "var(--red-10)",
        50: "var(--red-5)",
      },
      green: {
        950: "var(--green-95)",
        900: "var(--green-90)",
        800: "var(--green-80)",
        700: "var(--green-70)",
        600: "var(--green-60)",
        500: "var(--green-50)",
        400: "var(--green-40)",
        300: "var(--green-30)",
        200: "var(--green-20)",
        100: "var(--green-10)",
        50: "var(--green-5)",
      },
      yellow: {
        950: "var(--yellow-95)",
        900: "var(--yellow-90)",
        800: "var(--yellow-80)",
        700: "var(--yellow-70)",
        600: "var(--yellow-60)",
        500: "var(--yellow-50)",
        400: "var(--yellow-40)",
        300: "var(--yellow-30)",
        200: "var(--yellow-20)",
        100: "var(--yellow-10)",
        50: "var(--yellow-5)",
      },
      neutral: {
        975: "var(--neutral-975)",
        950: "var(--neutral-950)",
        925: "var(--neutral-925)",
        900: "var(--neutral-900)",
        850: "var(--neutral-850)",
        800: "var(--neutral-800)",
        750: "var(--neutral-750)",
        700: "var(--neutral-700)",
        650: "var(--neutral-650)",
        600: "var(--neutral-600)",
        550: "var(--neutral-550)",
        500: "var(--neutral-500)",
        450: "var(--neutral-450)",
        400: "var(--neutral-400)",
        350: "var(--neutral-350)",
        300: "var(--neutral-300)",
        250: "var(--neutral-250)",
        200: "var(--neutral-200)",
        150: "var(--neutral-150)",
        100: "var(--neutral-100)",
        75: "var(--neutral-75)",
        50: "var(--neutral-50)",
        25: "var(--neutral-25)",
      },
    },
    extend: {
      container: {
        center: true, // Centers the container
        padding: "2rem", // Adds padding around the container
      },
      screens: {
        xl: "1600px",
        "2xl": "1920px",
      },
      colors: {
        primary: {
          DEFAULT: "var(--primary)",
          90: "var(--primary-90)",
          85: "var(--primary-85)",
          80: "var(--primary-80)",
          75: "var(--primary-75)",
          70: "var(--primary-70)",
          65: "var(--primary-65)",
          60: "var(--primary-60)",
          55: "var(--primary-55)",
          50: "var(--primary-50)",
          45: "var(--primary-45)",
          40: "var(--primary-40)",
          35: "var(--primary-35)",
          30: "var(--primary-30)",
          25: "var(--primary-25)",
          20: "var(--primary-20)",
          15: "var(--primary-15)",
          10: "var(--primary-10)",
          5: "var(--primary-5)",
          "50-10": "#E76A4C1A",
          foreground: "var(--primary-foreground)",
          background: "var(--primary-background)",
          "on-background-default": "var(--primary-on-background-default)",
          "on-background-subdued": "var(--primary-on-background-subdued)",
          "on-background-active": "var(--primary-on-background-active)",
          "on-background-cta": "var(--primary-on-background-cta)",
          "on-background-disabled": "var(--primary-on-background-disabled)",
          "background-tint": "var(--primary-background-tint)",
          "background-tint-default": "var(--primary-background-tint-default)",
          "background-tint-disabled": "var(--primary-background-tint-disabled)",
        },
        neutral: {
          background: "var(--neutral-background)",
          foreground: "var(--neutral-foreground)",
          "foreground-disabled": "var(--neutral-foreground-disabled)",
          "foreground-subdued": "var(--neutral-foreground-subdued)",
          "on-foreground": "var(--neutral-on-foreground)",
          "on-foreground-disabled": "var(--neutral-on-foreground-disabled)",
          "on-foreground-cta": "var(--neutral-on-foreground-cta)",
          "background-2": "var(--neutral-background-2)",
          "background-3": "var(--neutral-background-3)",
          "background-4": "var(--neutral-background-4)",
          "background-tint": "var(--neutral-background-tint)",
          "on-background": "var(--neutral-on-background-default)",
          "on-background-subdued": "var(--neutral-on-background-subdued)",
          "on-background-active": "var(--neutral-on-background-active)",
          "on-background-cta": "var(--neutral-on-background-cta)",
          "on-background-disabled": "var(--neutral-on-background-disabled)",
          "on-background-tint": "var(--neutral-on-background-tint)",
          "stroke-1": "var(--neutral-stroke-1)",
          "stroke-2": "var(--neutral-stroke-2)",
          "stroke-2-active": "var(--neutral-stroke-2-active)",
          "stroke-2-error": "var(--neutral-stroke-2-error)",
          "stroke-2-hover": "var(--neutral-stroke-2-hover)",
          "stroke-3": "var(--neutral-stroke-3)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
        },
        success: {
          DEFAULT: "var(--success-foreground)",
          "on-background-default": "var(--success-on-background-default)",
          "on-background-subdued": "var(--success-on-background-subdued)",
          "on-background-disabled": "var(--success-on-background-disabled)",
          "on-background-tint": "var(--success-on-background-tint)",
          "background-tint": "var(--success-background-tint)",
        },
        warning: {
          DEFAULT: "var(--warning-foreground)",
          foreground: "var(--warning-foreground)",
          "on-background-subdued": "var(--warning-on-background-subdued)",
          "on-background-disabled": "var(--warning-on-background-disabled)",
          "on-background-tint": "var(--warning-on-background-tint)",
          "background-tint": "var(--warning-background-tint)",
        },
        error: {
          DEFAULT: "var(--error-foreground)",
          foreground: "var(--error-foreground)",
          "on-background-subdued": "var(--error-on-background-subdued)",
          "on-background-default": "var(--error-on-background-default)",
          "on-background-disabled": "var(--error-on-background-disabled)",
          "on-background-tint": "var(--error-on-background-tint)",
          "background-tint": "var(--error-background-tint)",
        },
        inverted: {
          DEFAULT: "var(--inverted-stroke)",
          stroke: "var(--inverted-stroke)",
          "stroke-2": "var(--inverted-stroke-2)",
        },
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
      fontSize: {
        caption: "var(--caption-medium-size)",
        "body-large": "var(--body-large-size)",
        "body-medium": "var(--body-medium-size)",
        "body-small": "var(--body-small-size)",
        "button-large": "var(--button-large-size)",
        "button-medium": "var(--button-medium-size)",
        "button-small": "var(--button-small-size)",
        "button-extra-small": "var(--button-extra-small-size)",
        "subtitle-large": "var(--subtitle-large-size)",
        "subtitle-medium": "var(--subtitle-medium-size)",
        "subtitle-small": "var(--subtitle-small-size)",
        "heading-1": "var(--heading-1-size)",
        "heading-2": "var(--heading-2-size)",
        "heading-3": "var(--heading-3-size)",
        "heading-4": "var(--heading-4-size)",
        "heading-5": "var(--heading-5-size)",
        "heading-6": "var(--heading-6-size)",
        "display-large": "var(--display-large-size)",
        "display-medium": "var(--display-medium-size)",
        "display-small": "var(--display-small-size)",
        //mobile-size
        "mobile-caption": "var(--mobile-caption-medium-size)",
        "mobile-body-large": "var(--mobile-body-large-size)",
        "mobile-body-medium": "var(--mobile-body-medium-size)",
        "mobile-body-small": "var(--mobile-body-small-size)",
        "mobile-button-large": "var(--mobile-button-large-size)",
        "mobile-button-medium": "var(--mobile-button-medium-size)",
        "mobile-button-small": "var(--mobile-button-small-size)",
        "mobile-button-extra-small": "var(--mobile-button-extra-small-size)",
        "mobile-subtitle-large": "var(--mobile-subtitle-large-size)",
        "mobile-subtitle-medium": "var(--mobile-subtitle-medium-size)",
        "mobile-subtitle-small": "var(--mobile-subtitle-small-size)",
        "mobile-heading-1": "var(--mobile-heading-1-size)",
        "mobile-heading-2": "var(--mobile-heading-2-size)",
        "mobile-heading-3": "var(--mobile-heading-3-size)",
        "mobile-heading-4": "var(--mobile-heading-4-size)",
        "mobile-heading-5": "var(--mobile-heading-5-size)",
        "mobile-heading-6": "var(--mobile-heading-6-size)",
        "mobile-display-large": "var(--mobile-display-large-size)",
        "mobile-display-medium": "var(--mobile-display-medium-size)",
        "mobile-display-small": "var(--mobile-display-small-size)",
        //tablet-size
        "tablet-caption": "var(--tablet-caption-medium-size)",
        "tablet-body-large": "var(--tablet-body-large-size)",
        "tablet-body-medium": "var(--tablet-body-medium-size)",
        "tablet-body-small": "var(--tablet-body-small-size)",
        "tablet-button-large": "var(--tablet-button-large-size)",
        "tablet-button-medium": "var(--tablet-button-medium-size)",
        "tablet-button-small": "var(--tablet-button-small-size)",
        "tablet-button-extra-small": "var(--tablet-button-extra-small-size)",
        "tablet-subtitle-large": "var(--tablet-subtitle-large-size)",
        "tablet-subtitle-medium": "var(--tablet-subtitle-medium-size)",
        "tablet-subtitle-small": "var(--tablet-subtitle-small-size)",
        "tablet-heading-1": "var(--tablet-heading-1-size)",
        "tablet-heading-2": "var(--tablet-heading-2-size)",
        "tablet-heading-3": "var(--tablet-heading-3-size)",
        "tablet-heading-4": "var(--tablet-heading-4-size)",
        "tablet-heading-5": "var(--tablet-heading-5-size)",
        "tablet-heading-6": "var(--tablet-heading-6-size)",
        "tablet-display-large": "var(--tablet-display-large-size)",
        "tablet-display-medium": "var(--tablet-display-medium-size)",
        "tablet-display-small": "var(--tablet-display-small-size)",
      },
      lineHeight: {
        caption: "var(--caption-medium-leading)",
        "body-large": "var(--body-large-leading)",
        "body-medium": "var(--body-medium-leading)",
        "body-small": "var(--body-small-leading)",
        "button-large": "var(--button-large-leading)",
        "button-medium": "var(--button-medium-leading)",
        "button-small": "var(--button-small-leading)",
        "button-extra-small": "var(--button-extra-small-leading)",
        "subtitle-large": "var(--subtitle-large-leading)",
        "subtitle-medium": "var(--subtitle-medium-leading)",
        "subtitle-small": "var(--subtitle-small-leading)",
        "heading-1": "var(--heading-1-leading)",
        "heading-2": "var(--heading-2-leading)",
        "heading-3": "var(--heading-3-leading)",
        "heading-4": "var(--heading-4-leading)",
        "heading-5": "var(--heading-5-leading)",
        "heading-6": "var(--heading-6-leading)",
        "display-large": "var(--display-large-leading)",
        "display-medium": "var(--display-medium-leading)",
        "display-small": "var(--display-small-leading)",
        //mobile leading
        "mobile-caption": "var(--mobile-caption-medium-leading)",
        "mobile-body-large": "var(--mobile-body-large-leading)",
        "mobile-body-medium": "var(--mobile-body-medium-leading)",
        "mobile-body-small": "var(--mobile-body-small-leading)",
        "mobile-button-large": "var(--mobile-button-large-leading)",
        "mobile-button-medium": "var(--mobile-button-medium-leading)",
        "mobile-button-small": "var(--mobile-button-small-leading)",
        "mobile-button-extra-small": "var(--mobile-button-extra-small-leading)",
        "mobile-subtitle-large": "var(--mobile-subtitle-large-leading)",
        "mobile-subtitle-medium": "var(--mobile-subtitle-medium-leading)",
        "mobile-subtitle-small": "var(--mobile-subtitle-small-leading)",
        "mobile-heading-1": "var(--mobile-heading-1-leading)",
        "mobile-heading-2": "var(--mobile-heading-2-leading)",
        "mobile-heading-3": "var(--mobile-heading-3-leading)",
        "mobile-heading-4": "var(--mobile-heading-4-leading)",
        "mobile-heading-5": "var(--mobile-heading-5-leading)",
        "mobile-heading-6": "var(--mobile-heading-6-leading)",
        "mobile-display-large": "var(--mobile-display-large-leading)",
        "mobile-display-medium": "var(--mobile-display-medium-leading)",
        "mobile-display-small": "var(--mobile-display-small-leading)",

        //tablet leading
        "tablet-caption": "var(--tablet-caption-medium-leading)",
        "tablet-body-large": "var(--tablet-body-large-leading)",
        "tablet-body-medium": "var(--tablet-body-medium-leading)",
        "tablet-body-small": "var(--tablet-body-small-leading)",
        "tablet-button-large": "var(--tablet-button-large-leading)",
        "tablet-button-medium": "var(--tablet-button-medium-leading)",
        "tablet-button-small": "var(--tablet-button-small-leading)",
        "tablet-button-extra-small": "var(--tablet-button-extra-small-leading)",
        "tablet-subtitle-large": "var(--tablet-subtitle-large-leading)",
        "tablet-subtitle-medium": "var(--tablet-subtitle-medium-leading)",
        "tablet-subtitle-small": "var(--tablet-subtitle-small-leading)",
        "tablet-heading-1": "var(--tablet-heading-1-leading)",
        "tablet-heading-2": "var(--tablet-heading-2-leading)",
        "tablet-heading-3": "var(--tablet-heading-3-leading)",
        "tablet-heading-4": "var(--tablet-heading-4-leading)",
        "tablet-heading-5": "var(--tablet-heading-5-leading)",
        "tablet-heading-6": "var(--tablet-heading-6-leading)",
        "tablet-display-large": "var(--tablet-display-large-leading)",
        "tablet-display-medium": "var(--tablet-display-medium-leading)",
        "tablet-display-small": "var(--tablet-display-small-leading)",
      },
      fontFamily: {
        cormorant: ["var(--font-cormorant)"],
      },
    },
  },
  plugins: [
    plugin(function ({ addUtilities }: { addUtilities: any }) {
      addUtilities({
        ".scrollbar-none": {
          "scrollbar-width": "none",
          "-ms-overflow-style": "none",
        },
        ".scrollbar-none::-webkit-scrollbar": {
          display: "none",
        },
      });
    }),
  ],
};
export default config;
